-- 002_chart_of_accounts.sql
-- Chart of Accounts for a fuel wholesale/retail company.
-- Numbering follows a 4-digit hierarchical convention:
--   1xxx Assets, 2xxx Liabilities, 3xxx Equity, 4xxx Revenue, 5xxx Cost of sales, 6xxx Operating expenses

-- Note: company_id below is the demo company seeded in 001_demo_company.sql.

WITH ppc AS (SELECT '11111111-1111-1111-1111-111111111111'::uuid AS id)
INSERT INTO accounts (company_id, code, name, account_type, is_control)
SELECT ppc.id, x.code, x.name, x.account_type, x.is_control FROM ppc, (VALUES
  -- ASSETS (1000-1999)
  ('1010', 'Petty cash',                             'ASSET',     false),
  ('1020', 'Cash on hand - retail stations',         'ASSET',     false),
  ('1030', 'Cash in bank - BPI Current',             'ASSET',     false),
  ('1031', 'Cash in bank - BDO Current',             'ASSET',     false),
  ('1040', 'Cash in bank - USD account',             'ASSET',     false),
  ('1100', 'Accounts receivable - trade',            'ASSET',     true),
  ('1110', 'Accounts receivable - fleet accounts',   'ASSET',     true),
  ('1120', 'Accounts receivable - employees',        'ASSET',     false),
  ('1190', 'Allowance for doubtful accounts',        'ASSET',     false),
  ('1200', 'Inventory - diesel',                     'ASSET',     false),
  ('1210', 'Inventory - gasoline 91',                'ASSET',     false),
  ('1220', 'Inventory - gasoline 95',                'ASSET',     false),
  ('1230', 'Inventory - gasoline 97',                'ASSET',     false),
  ('1240', 'Inventory - kerosene',                   'ASSET',     false),
  ('1250', 'Inventory - LPG',                        'ASSET',     false),
  ('1290', 'Inventory - lubricants and additives',   'ASSET',     false),
  ('1295', 'Inventory in transit',                   'ASSET',     false),
  ('1300', 'Input VAT',                              'ASSET',     true),
  ('1310', 'Creditable withholding tax',             'ASSET',     false),
  ('1320', 'Excise tax - prepaid',                   'ASSET',     false),
  ('1400', 'Prepaid expenses',                       'ASSET',     false),
  ('1410', 'Advances to suppliers',                  'ASSET',     false),
  ('1500', 'PPE - Land',                             'ASSET',     false),
  ('1510', 'PPE - Buildings',                        'ASSET',     false),
  ('1520', 'PPE - Storage tanks',                    'ASSET',     false),
  ('1530', 'PPE - Pumps and dispensers',             'ASSET',     false),
  ('1540', 'PPE - Tankers and vehicles',             'ASSET',     false),
  ('1550', 'PPE - Furniture and equipment',          'ASSET',     false),
  ('1599', 'Accumulated depreciation',               'ASSET',     false),
  -- LIABILITIES (2000-2999)
  ('2010', 'Accounts payable - trade',               'LIABILITY', true),
  ('2020', 'Accounts payable - refineries',          'LIABILITY', true),
  ('2100', 'Accrued expenses',                       'LIABILITY', false),
  ('2110', 'Accrued salaries and wages',             'LIABILITY', false),
  ('2200', 'Output VAT',                             'LIABILITY', true),
  ('2210', 'VAT payable',                            'LIABILITY', false),
  ('2220', 'Excise tax payable',                     'LIABILITY', false),
  ('2230', 'EWT payable',                            'LIABILITY', false),
  ('2240', 'Withholding tax on compensation payable','LIABILITY', false),
  ('2250', 'SSS premiums payable',                   'LIABILITY', false),
  ('2260', 'PhilHealth premiums payable',            'LIABILITY', false),
  ('2270', 'Pag-IBIG premiums payable',              'LIABILITY', false),
  ('2300', 'Customer deposits',                      'LIABILITY', false),
  ('2310', 'Unearned revenue',                       'LIABILITY', false),
  ('2400', 'Short-term loans payable',               'LIABILITY', false),
  ('2500', 'Long-term loans payable',                'LIABILITY', false),
  -- EQUITY (3000-3999)
  ('3010', 'Share capital',                          'EQUITY',    false),
  ('3020', 'Retained earnings',                      'EQUITY',    false),
  ('3030', 'Current year earnings',                  'EQUITY',    false),
  -- REVENUE (4000-4999)
  ('4010', 'Sales - diesel',                         'REVENUE',   false),
  ('4020', 'Sales - gasoline 91',                    'REVENUE',   false),
  ('4030', 'Sales - gasoline 95',                    'REVENUE',   false),
  ('4040', 'Sales - gasoline 97',                    'REVENUE',   false),
  ('4050', 'Sales - kerosene',                       'REVENUE',   false),
  ('4060', 'Sales - LPG',                            'REVENUE',   false),
  ('4090', 'Sales - lubricants and additives',       'REVENUE',   false),
  ('4100', 'Sales discounts',                        'REVENUE',   false),
  ('4110', 'Sales returns and allowances',           'REVENUE',   false),
  ('4200', 'Other revenue - delivery charges',       'REVENUE',   false),
  ('4210', 'Interest income',                        'REVENUE',   false),
  ('4220', 'FX gain',                                'REVENUE',   false),
  -- COST OF SALES (5000-5499)
  ('5010', 'COGS - diesel',                          'EXPENSE',   false),
  ('5020', 'COGS - gasoline 91',                     'EXPENSE',   false),
  ('5030', 'COGS - gasoline 95',                     'EXPENSE',   false),
  ('5040', 'COGS - gasoline 97',                     'EXPENSE',   false),
  ('5050', 'COGS - kerosene',                        'EXPENSE',   false),
  ('5060', 'COGS - LPG',                             'EXPENSE',   false),
  ('5090', 'COGS - lubricants and additives',        'EXPENSE',   false),
  ('5200', 'Inventory variance - fuel losses',       'EXPENSE',   false),
  ('5210', 'Inventory variance - evaporation',       'EXPENSE',   false),
  ('5220', 'Freight in / hauling cost',              'EXPENSE',   false),
  -- OPERATING EXPENSES (6000-6999)
  ('6010', 'Salaries and wages',                     'EXPENSE',   false),
  ('6020', 'Employee benefits',                      'EXPENSE',   false),
  ('6030', 'SSS / PhilHealth / Pag-IBIG employer',   'EXPENSE',   false),
  ('6100', 'Rent - station and office',              'EXPENSE',   false),
  ('6110', 'Utilities - electricity',                'EXPENSE',   false),
  ('6120', 'Utilities - water and telco',            'EXPENSE',   false),
  ('6130', 'Repairs and maintenance',                'EXPENSE',   false),
  ('6140', 'Fuel and oil - vehicles',                'EXPENSE',   false),
  ('6150', 'Transportation and travel',              'EXPENSE',   false),
  ('6160', 'Office supplies',                        'EXPENSE',   false),
  ('6200', 'Depreciation expense',                   'EXPENSE',   false),
  ('6210', 'Insurance',                              'EXPENSE',   false),
  ('6220', 'Taxes and licenses',                     'EXPENSE',   false),
  ('6230', 'Professional fees',                      'EXPENSE',   false),
  ('6240', 'Bank charges',                           'EXPENSE',   false),
  ('6250', 'Marketing and advertising',              'EXPENSE',   false),
  ('6900', 'Miscellaneous expense',                  'EXPENSE',   false),
  ('6910', 'FX loss',                                'EXPENSE',   false)
) AS x(code, name, account_type, is_control)
ON CONFLICT (company_id, code) DO NOTHING;
